# gin
gin:
  server: # server 配置
    mode: debug # server mode: release, debug, test，默认 release
    healthz: true # 是否开启健康检查，如果开启会安装 /healthz 路由，默认 true
    middlewares: recovery,logger,secure,nocache,cors,dump # 加载的 gin 中间件列表，多个中间件，逗号(,)隔开
    max-ping-count: 3 # http 服务启动后，自检尝试次数，默认 3

  # HTTP 配置
  insecure:
    bind-address: 127.0.0.1 # 绑定的不安全 IP 地址，设置为 0.0.0.0 表示使用全部网络接口，默认为 127.0.0.1
    bind-port: 8080 # 提供非安全认证的监听端口，默认为 8080

  # HTTPS 配置
  secure:
    bind-address: 127.0.0.1 # HTTPS 安全模式的 IP 地址，默认为 0.0.0.0
    bind-port: 8443 # 使用 HTTPS 安全模式的端口号，设置为 0 表示不启用 HTTPS，默认为 8443
    tls:
      cert-file: /Users/ruan/workspace/go/60_paas/20_db/10_mysql/80_server/configs/cert/server.pem # 包含 x509 证书的文件路径，用 HTTPS 认证
      private-key-file: /Users/ruan/workspace/go/60_paas/20_db/10_mysql/80_server/configs/cert/server.key # TLS 私钥

# GRPC 服务配置
grpc:
  bind-address: 127.0.0.1 # grpc 安全模式的 IP 地址，默认 0.0.0.0
  bind-port: 8081 # grpc 安全模式的端口号，默认 8081

# MySQL 数据库相关配置
mysql:
  host: 127.0.0.1:3306 # MySQL 机器 ip 和端口，默认 127.0.0.1:3306
  username: root # MySQL 用户名(建议授权最小权限集)
  password: Heruan1214++ # MySQL 用户密码
  database: iam # iam 系统所用的数据库名



