basePath: /
definitions:
  model.User:
    properties:
      address:
        type: string
      age:
        type: integer
      id:
        type: integer
      mobile:
        type: string
      name:
        type: string
      sex:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    name: wukong
    url: http://www.xxx.io/support
  description: This is a Gin Swag server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin Swag 案例
  version: "1.0"
paths:
  /user/{id}/{name}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: NAME
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: UserController 接口
      tags:
      - Name
swagger: "2.0"
